export const IPC = {
  GET_SCREENSHOT: 'screenshot:getData',
  GET_TEAMS: 'linear:getTeams',
  GET_PROJECTS: 'linear:getProjects',
  GET_WORKFLOW_STATES: 'linear:getWorkflowStates',
  GET_LABELS: 'linear:getLabels',
  GET_MEMBERS: 'linear:getMembers',
  SEARCH_ISSUES: 'linear:searchIssues',
  GET_RECENT_ISSUES: 'linear:getRecentIssues',
  CREATE_ISSUE: 'linear:createIssue',
  ADD_COMMENT: 'linear:addComment',
  GET_API_KEY: 'store:getApiKey',
  SET_API_KEY: 'store:setApiKey',
  GET_ENABLED: 'store:getEnabled',
  SET_ENABLED: 'store:setEnabled',
  OPEN_SETTINGS: 'app:openSettings',
  CLOSE_WINDOW: 'app:closeWindow',
  GET_RECENT_SELECTIONS: 'store:getRecentSelections',
  SAVE_LAST_TEAM: 'store:saveLastTeam',
  SAVE_LAST_PROJECT: 'store:saveLastProject',
  SAVE_RECENT_TICKET: 'store:saveRecentTicket',
  GET_HOTKEY: 'store:getHotkey',
  SET_HOTKEY: 'store:setHotkey',
  SHOW_TOAST: 'app:showToast',
  CREATE_ISSUE_BG: 'linear:createIssueBg',
  ADD_COMMENT_BG: 'linear:addCommentBg',
} as const;
