import { contextBridge, ipcRenderer } from 'electron';
import { IPC } from '../shared/ipc-channels';

contextBridge.exposeInMainWorld('api', {
  getScreenshot: () => ipcRenderer.invoke(IPC.GET_SCREENSHOT),
  getScreenshotQueue: () => ipcRenderer.invoke(IPC.GET_SCREENSHOT_QUEUE),
  getTeams: () => ipcRenderer.invoke(IPC.GET_TEAMS),
  getProjects: () => ipcRenderer.invoke(IPC.GET_PROJECTS),
  getWorkflowStates: (teamId: string) => ipcRenderer.invoke(IPC.GET_WORKFLOW_STATES, teamId),
  getLabels: (teamId: string) => ipcRenderer.invoke(IPC.GET_LABELS, teamId),
  getMembers: (teamId: string) => ipcRenderer.invoke(IPC.GET_MEMBERS, teamId),
  searchIssues: (query: string) => ipcRenderer.invoke(IPC.SEARCH_ISSUES, query),
  getRecentIssues: () => ipcRenderer.invoke(IPC.GET_RECENT_ISSUES),
  createIssue: (input: unknown) => ipcRenderer.invoke(IPC.CREATE_ISSUE, input),
  addComment: (input: unknown) => ipcRenderer.invoke(IPC.ADD_COMMENT, input),
  getApiKey: () => ipcRenderer.invoke(IPC.GET_API_KEY),
  setApiKey: (key: string) => ipcRenderer.invoke(IPC.SET_API_KEY, key),
  getEnabled: () => ipcRenderer.invoke(IPC.GET_ENABLED),
  setEnabled: (enabled: boolean) => ipcRenderer.invoke(IPC.SET_ENABLED, enabled),
  getHotkey: () => ipcRenderer.invoke(IPC.GET_HOTKEY),
  setHotkey: (hotkey: string) => ipcRenderer.invoke(IPC.SET_HOTKEY, hotkey),
  getCollectHotkey: () => ipcRenderer.invoke(IPC.GET_COLLECT_HOTKEY),
  setCollectHotkey: (hotkey: string) => ipcRenderer.invoke(IPC.SET_COLLECT_HOTKEY, hotkey),
  getOpenQueueHotkey: () => ipcRenderer.invoke(IPC.GET_OPEN_QUEUE_HOTKEY),
  setOpenQueueHotkey: (hotkey: string) => ipcRenderer.invoke(IPC.SET_OPEN_QUEUE_HOTKEY, hotkey),
  openSettings: () => ipcRenderer.invoke(IPC.OPEN_SETTINGS),
  closeWindow: () => ipcRenderer.invoke(IPC.CLOSE_WINDOW),
  getRecentSelections: () => ipcRenderer.invoke(IPC.GET_RECENT_SELECTIONS),
  saveLastTeam: (teamId: string) => ipcRenderer.invoke(IPC.SAVE_LAST_TEAM, teamId),
  saveLastProject: (projectId: string) => ipcRenderer.invoke(IPC.SAVE_LAST_PROJECT, projectId),
  saveRecentTicket: (ticket: unknown) => ipcRenderer.invoke(IPC.SAVE_RECENT_TICKET, ticket),
  showToast: (data: { title: string; body: string; url: string }) => ipcRenderer.invoke(IPC.SHOW_TOAST, data),
  createIssueBg: (input: unknown) => ipcRenderer.invoke(IPC.CREATE_ISSUE_BG, input),
  addCommentBg: (input: unknown) => ipcRenderer.invoke(IPC.ADD_COMMENT_BG, input),
  checkForUpdates: () => ipcRenderer.invoke(IPC.CHECK_FOR_UPDATES),
  getAppVersion: () => ipcRenderer.invoke(IPC.GET_APP_VERSION),
  openExternal: (url: string) => ipcRenderer.invoke(IPC.OPEN_EXTERNAL, url),
});
